### PR TITLE
Two patches to improve onion_shortcut_rename

### PR DESCRIPTION
**Pull request by nashidau**

### CODE REVIEW

**Comment by davidmoreno** [comment]
Hi,

I saw an error, could you fix it? then I will just accept the patch.

Thanks!

**Comment by nashidau** [comment]
Can you be more specific?
Master builds with the changes.

The first patch adds | O_TRUNC to the open options.  The second reverses the order that source & destination.  View them individually and it's much clearer, the merged diff is a little weird.

**Comment by davidmoreno** [comment]
Hi,

on shortcuts.c:382 you assign fd_orig, but on 383 check fd_dest. I think this bug was there before.

All the rest sound good to me.

**Comment by nashidau** [comment]
Yes it was there before ;-)
I've got a new commit for it, I'll send it by itself if you want to land these first?
/me hates github pull requests

**Comment by davidmoreno** [comment]
Thanks! Merged!

**Pull request merged**
