### PR TITLE
Added a call to the pthread_rwlock_rdlock.

### PR DESCRIPTION
**Pull request by zacharygrafton**
We need to lock on the reading of onion_response_last_time as it's
protected by the onion_response_date_lock.

### CODE REVIEW

**Comment by davidmoreno** [comment]
I'm not sure we need that lock.

The thing is that the test of t!=onion_response_last_time is an optimistic optimization. It its equal we know we can use whatever is at onion_response_last_date_header (which we properly use with locks). If its different (different time or some "ephemeral" moment because the memory is half written), then we recalculate the onion_response_last_date_header. So in the worst case we just recalculate the header. But if equal, we go on with the old one. The proper way would be to use some atomic get instruction, but I think we prefer to use C99, so not an option.

I guess this problem was detected by the clang thread sanitize... so it may be a false positive. 

Actually to add this check might not be important, so I'm ok to add it if there is no performance regression. 

Did you do some performance tests?

David.

**Comment by zacharygrafton** [comment]
I didn't really notice a performance hit, but I was running the before/after checks with the thread sanitizer, so the results probably aren't reliable. The thread sanitizer doesn't really give false positives as it's check the reads/writes to the memory location at runtime. We are definitely reading the variable from one thread and writing to it in another at the same time. Technically, that is a data race either way and is classified as undefined behavior. Now, I don't think it really matters in the case, but I usually try to avoid UB as much as possible.

I wasn't really sure about submitting this pull request but I thought that starting a conversation about it would be useful. Also, on the mailing list, I mentioned sticking to C99, but in a follow up you responded with the suggestion that we could just require C11 and C++11 as minimum compiler requirements, so I'm open to suggestions. Also, there is the opportunity to use compiler intrinsics for atomic operations as well, which could fix this problem. I'll take a look at it and update the request.

**Comment by zacharygrafton** [comment]
So, after looking into the atomics a bit further, I was unable to get it to appease the thread sanitizer using the older __sync intrinsics, however, I was able to use C11 atomics successfully. Unfortunately that would mean minimum required version of gcc would be 4.9. So, I'm not sure if we should merge this patch or not.

**Comment by solardiz** [comment]
> I was unable to get it to appease the thread sanitizer using the older __sync intrinsics

I'd expect __sync_add_and_fetch(&var, 0) to work, as long as time_t happens to correspond to a supported type.

**Comment by zacharygrafton** [comment]
I had tried that, it was the corresponding store that I could not get to function correctly. I even tried wrapping the store in ```__sync_synchronize()``` calls. The ```time_t``` structure on my machine is just and ```long int``` so it should work...

**Comment by zacharygrafton** [comment]
Nevermind, I got it to work correctly and appease the thread sanitizer. Apparently I was using the wrong variable for the compare and swap.

**Pull request merged**
