### PR TITLE
C++ binding work

### PR DESCRIPTION
**Pull request by zacharygrafton**
Updated some of the documentation to use more natural English. Also, updated portions of the C++ bindings to use C++11 automatic memory management.

### CODE REVIEW

**Comment by davidmoreno** [comment]
Hi,

thanks a lot for the work!

Almost everything looks great, but I would very much prefer the dict most used methods to be inlined into the header, so they are transparently inlined into their respective uses, avoiding one extra function call.

Normally this makes no real performance difference, but I think that dict access as it is quite common, and normally just calls a C function, it is worth just inlining it.

This would be the [] operator, get, set, count and maybe basic construction from onion_dict*.

For the url.hpp, looks great passing it all to the cpp file. At the begining I aimed for an only header C++ binding, but thats almost impossibl and does not worth the effort. 

Looking forward for your thoughts and or  changes.

Regards,
David

**Comment by davidmoreno** [comment]
Hi,

thanks a lot for the work!

Almost everything looks great, but I would very much prefer the dict most used methods to be inlined into the header, so they are transparently inlined into their respective uses, avoiding one extra function call.

Normally this makes no real performance difference, but I think that dict access as it is quite common, and normally just calls a C function, it is worth just inlining it.

This would be the [] operator, get, set, count and maybe basic construction from onion_dict*.

For the url.hpp, looks great passing it all to the cpp file. At the begining I aimed for an only header C++ binding, but thats almost impossibl and does not worth the effort. 

Looking forward for your thoughts and or  changes.

Regards,
David

**Comment by zacharygrafton** [comment]
David,

I thought about those use cases as well. My thinking was that if Onion was being linked statically, the method calls would be inlined during the link phase if the user was using LTO. In the case of the shared object, sometimes those definitions in the header can violate the one definition rule. I know I've run into those issues when doing unity builds of my projects. I think a header only solution seems impractical as well.

Either way, I can pull those methods out into the header if you would like it better that way.

Thanks,
Zack

**Comment by davidmoreno** [comment]
You are right on the static lib case, but the dynamic still exists, so for
very small inlineable and very used methods, I prefer them inline.

Thanks

**Comment by zacharygrafton** [comment]
Hi David,

I made the requested changes, let me know what you think.

Thanks,
Zack

**Comment by davidmoreno** [comment]
Thanks a lot!

If you find any other areas of improvement, please send me more pull requests.

**Pull request merged**
