### PR TITLE
Bugfix in `onion_response_vprintf`

### PR DESCRIPTION
**Pull request by remibd**
Hi!

Here is a simple bugfix for some quirks with inputs larger than 512 bytes in `response.c:onion_response_vprintf`:
- the `va_list args` parameter was used twice, which is an undefined behavior (see `man 3 va_copy`), leading to segfaults on my machine;
- the second `vsnprintf`’s output was truncated, leading to the sending of a NUL character.

Beware: I have been unable to run the tests (couldn’t find how to do in `README.md`), therefore this request might break everything…

Sincerely,

### CODE REVIEW

**Comment by davidmoreno** [comment]
Hi,

main tests are compiled at tests/01-internal/. Can be run at test/auto.sh.

I will run them now to check your patch.

Which distro/OS were you using?

David.

**Comment by davidmoreno** [comment]
Thanks, all ok. I guess I was not doing printfs with more than 512 characters. Adding the test now.

BTW some tests fail, but the important one, 03-response works ok with this patch.

**Comment by davidmoreno** [comment]
Ok, test added at https://github.com/davidmoreno/onion/blob/master/tests/01-internal/03-response.c#L233

**Comment by remibd** [comment]
Thank you!
I’m using Archlinux 64:
`Linux 4.5.1-1-ARCH #1 SMP PREEMPT Thu Apr 14 19:19:32 CEST 2016 x86_64 GNU/Linux`.

**Pull request merged**
