### PR TITLE
Only add_subdirectory(tests) for ONION_USE_TESTS

### PR DESCRIPTION
**Pull request by jeffvandyke**
This allows users of this project that incorporate it into their CMake buildsystem to optionally avoid needing to compile the tests for a clean build. If tests aren't run, then (maybe I'm wrong) I don't see a need to compile them.

### CODE REVIEW

**Comment by davidmoreno** [comment]
Maybe we should also enable tests by default (so just flip the ONION_USE_TEST to default true at the beginning of file).

What do you think?

**Comment by jeffvandyke** [comment]
Just finished testing it, and that should work fine, and it makes sense if by default we're compiling the examples as well.

**Comment by davidmoreno** [comment]
Sorry, took me some days to be able to look into it. All passing now on my laptop. 

There was only one problem on the websocket test running because of a compile time requirement.

**Comment by jeffvandyke** [comment]
No problem, you're doing pretty good for time compared to some of the other projects I've seen :smile:

**Pull request merged**
